// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: pb/addressbook/addressbook.proto

package addressbook

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddressInfoClient is the client API for AddressInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddressInfoClient interface {
	//定義api名稱，傳入參數與回傳值
	GetAddressInfo(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
}

type addressInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressInfoClient(cc grpc.ClientConnInterface) AddressInfoClient {
	return &addressInfoClient{cc}
}

func (c *addressInfoClient) GetAddressInfo(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/addressbook.AddressInfo/GetAddressInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressInfoServer is the server API for AddressInfo service.
// All implementations must embed UnimplementedAddressInfoServer
// for forward compatibility
type AddressInfoServer interface {
	//定義api名稱，傳入參數與回傳值
	GetAddressInfo(context.Context, *Person) (*Person, error)
	mustEmbedUnimplementedAddressInfoServer()
}

// UnimplementedAddressInfoServer must be embedded to have forward compatible implementations.
type UnimplementedAddressInfoServer struct {
}

func (UnimplementedAddressInfoServer) GetAddressInfo(context.Context, *Person) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressInfo not implemented")
}
func (UnimplementedAddressInfoServer) mustEmbedUnimplementedAddressInfoServer() {}

// UnsafeAddressInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressInfoServer will
// result in compilation errors.
type UnsafeAddressInfoServer interface {
	mustEmbedUnimplementedAddressInfoServer()
}

func RegisterAddressInfoServer(s grpc.ServiceRegistrar, srv AddressInfoServer) {
	s.RegisterService(&AddressInfo_ServiceDesc, srv)
}

func _AddressInfo_GetAddressInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressInfoServer).GetAddressInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addressbook.AddressInfo/GetAddressInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressInfoServer).GetAddressInfo(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

// AddressInfo_ServiceDesc is the grpc.ServiceDesc for AddressInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddressInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "addressbook.AddressInfo",
	HandlerType: (*AddressInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddressInfo",
			Handler:    _AddressInfo_GetAddressInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/addressbook/addressbook.proto",
}
