// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: pb/userInfo/userInfo.proto

package userInfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfoRes_Gender int32

const (
	UserInfoRes_MALE   UserInfoRes_Gender = 0
	UserInfoRes_FEMALE UserInfoRes_Gender = 1
)

// Enum value maps for UserInfoRes_Gender.
var (
	UserInfoRes_Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
	}
	UserInfoRes_Gender_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
	}
)

func (x UserInfoRes_Gender) Enum() *UserInfoRes_Gender {
	p := new(UserInfoRes_Gender)
	*p = x
	return p
}

func (x UserInfoRes_Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserInfoRes_Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_userInfo_userInfo_proto_enumTypes[0].Descriptor()
}

func (UserInfoRes_Gender) Type() protoreflect.EnumType {
	return &file_pb_userInfo_userInfo_proto_enumTypes[0]
}

func (x UserInfoRes_Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserInfoRes_Gender.Descriptor instead.
func (UserInfoRes_Gender) EnumDescriptor() ([]byte, []int) {
	return file_pb_userInfo_userInfo_proto_rawDescGZIP(), []int{1, 0}
}

//傳入參數的spec
type UserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_userInfo_userInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_userInfo_userInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_pb_userInfo_userInfo_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

//回傳值的spec
type UserInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender  UserInfoRes_Gender `protobuf:"varint,2,opt,name=gender,proto3,enum=UserInfoRes_Gender" json:"gender,omitempty"`
	Habbits []string           `protobuf:"bytes,3,rep,name=habbits,proto3" json:"habbits,omitempty"`
}

func (x *UserInfoRes) Reset() {
	*x = UserInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_userInfo_userInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRes) ProtoMessage() {}

func (x *UserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_userInfo_userInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRes.ProtoReflect.Descriptor instead.
func (*UserInfoRes) Descriptor() ([]byte, []int) {
	return file_pb_userInfo_userInfo_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoRes) GetGender() UserInfoRes_Gender {
	if x != nil {
		return x.Gender
	}
	return UserInfoRes_MALE
}

func (x *UserInfoRes) GetHabbits() []string {
	if x != nil {
		return x.Habbits
	}
	return nil
}

var File_pb_userInfo_userInfo_proto protoreflect.FileDescriptor

var file_pb_userInfo_userInfo_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0b,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x62, 0x62, 0x69, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x68, 0x61, 0x62, 0x62, 0x69, 0x74, 0x73, 0x22, 0x1e,
	0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x32, 0x37,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0c, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_userInfo_userInfo_proto_rawDescOnce sync.Once
	file_pb_userInfo_userInfo_proto_rawDescData = file_pb_userInfo_userInfo_proto_rawDesc
)

func file_pb_userInfo_userInfo_proto_rawDescGZIP() []byte {
	file_pb_userInfo_userInfo_proto_rawDescOnce.Do(func() {
		file_pb_userInfo_userInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_userInfo_userInfo_proto_rawDescData)
	})
	return file_pb_userInfo_userInfo_proto_rawDescData
}

var file_pb_userInfo_userInfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_userInfo_userInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_userInfo_userInfo_proto_goTypes = []interface{}{
	(UserInfoRes_Gender)(0), // 0: UserInfoRes.Gender
	(*UserInfoReq)(nil),     // 1: UserInfoReq
	(*UserInfoRes)(nil),     // 2: UserInfoRes
}
var file_pb_userInfo_userInfo_proto_depIdxs = []int32{
	0, // 0: UserInfoRes.gender:type_name -> UserInfoRes.Gender
	1, // 1: UserInfo.GetUserInfo:input_type -> UserInfoReq
	2, // 2: UserInfo.GetUserInfo:output_type -> UserInfoRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_userInfo_userInfo_proto_init() }
func file_pb_userInfo_userInfo_proto_init() {
	if File_pb_userInfo_userInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_userInfo_userInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_userInfo_userInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_userInfo_userInfo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_userInfo_userInfo_proto_goTypes,
		DependencyIndexes: file_pb_userInfo_userInfo_proto_depIdxs,
		EnumInfos:         file_pb_userInfo_userInfo_proto_enumTypes,
		MessageInfos:      file_pb_userInfo_userInfo_proto_msgTypes,
	}.Build()
	File_pb_userInfo_userInfo_proto = out.File
	file_pb_userInfo_userInfo_proto_rawDesc = nil
	file_pb_userInfo_userInfo_proto_goTypes = nil
	file_pb_userInfo_userInfo_proto_depIdxs = nil
}
